import type { Metadata } from "next";

import { Header, Navigation } from "@/components/header";
import Settings from "@/components/settings";
import Categories from "./_components/categories";
import { getAllCategories } from "@/queries";
// import { usePathname, useSearchParams } from "next/navigation";

export const metadata: Metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};

export default async function DuasLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategories();
  return (
    <div className="px-4 lg:px-6 h-screen grid xl:py-6 lg:grid-cols-[380px,1fr] gap-x-4 grid-rows-[92px,1fr,64px] xl:grid-cols-[80px,380px,1fr] 2xl:grid-cols-[100px,430px,1fr,270px]">
      <div className="row-start-1 col-span-4 -mx-4 lg:-mx-6 xl:m-0">
        <Header />
      </div>
      <div className="row-start-3 col-span-4 xl:row-start-1 xl:row-span-3 xl:col-start-1 xl:col-span-1 -mx-4 lg:-mx-6 xl:m-0">
        <Navigation />
      </div>
      <Categories categories={categories} />
      {children}
      <div className="hidden 2xl:block xl:row-span-2">
        <Settings />
      </div>
    </div>
  );
}
