import type { Metadata } from "next";
import "./globals.css";

import { Poppins, Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins-sans",
});

const inter = Inter({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-inter-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} bg-gray-300 font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
